apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml -o petclinic_chart/templates
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: mysql-server
  name: mysql-server
spec:
  type: ExternalName
  externalName: petclinic.csh4u6m8281i.us-east-1.rds.amazonaws.com # Change this line with the endpoint of your RDS.
